export const FETCH_POSTS = 'POST/FETCH_POSTS';
export const FETCH_COMMENTS = 'POST/FETCH_COMMENTS';
export const REQUEST_POSTS = 'POST/REQUEST_POSTS';
export const REQUEST_COMMENTS = 'POST/REQUEST_COMMENTS';
export const REQUEST_USERS = 'REQUEST_USERS';
export const FETCH_USERS = 'FETCH_USERS';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
